GET http://localhost:3001/bot-score?names=FilterToxic,italodeandra
Authorization: Bearer eyJpZCI6IjQ3MTQ5NTc0NjkiLCJzY3JlZW5OYW1lIjoiaXRhbG9kZWFuZHJhIiwiYWNjZXNzVG9rZW4iOiI0NzE0OTU3NDY5LTh5SVowQThuUkQ5cmpDVGhGQm9sV0E4OThQb2I2bFhqdUpSdEs3TCIsImFjY2Vzc1Rva2VuU2VjcmV0IjoiREZWU1ZDd2o2eXpSNmpFcWdCNzREMTk1b1JhMWpMZTdoNWZRNEdOdGZzb01OIiwibmFtZSI6Is10YWxvIEFuZHJhZGUiLCJwcm9maWxlSW1hZ2VVcmwiOiJodHRwczovL3Bicy50d2ltZy5jb20vcHJvZmlsZV9pbWFnZXMvMTI0NjEyNjczNDg3NDkzOTM5Mi9BMXd1SzNyN19ub3JtYWwuanBnIn0=

###